# ~/.config/lazygit/config.yml
# (Create the directory and file if they don't exist)

gui:
  theme:
    activeBorderColor:
      - '#d79921'
      - bold
    inactiveBorderColor:
      - '#504945'
    optionsTextColor:
      - '#ebdbb2'
    selectedLineBgColor:
      - '#504945'
    selectedRangeBgColor:
      - '#665c54'
    cherryPickedCommitBgColor:
      - '#689d6a'
    cherryPickedCommitFgColor:
      - '#282828'
    unstagedChangesColor:
      - '#cc241d'
    defaultFgColor:
      - '#ebdbb2'
    searchingActiveBorderColor:
      - '#fb4934'
      - bold

    tagColor:
      - '#d79921'
      - bold
    branchColor:
      - '#b16286'
      - bold
    commitColor:
      - '#ebdbb2'
    unstagedFilesColor:
      - '#cc241d'
    stagedFilesColor:
      - '#98971a'
    mergingConflictsColor:
      - '#d65d0e'
      - bold
    diffTerminalColor:
      - '#ebdbb2'

# You can add other lazygit configurations below this line
# os:
#   edit: 'nvim'
