#!/usr/bin/env bash

#    ____ ____  ______        ____  __ 
#   | __ ) ___||  _ \ \      / /  \/  |  - z0mbi3
#   |  _ \___ \| |_) \ \ /\ / /| |\/| |  - https://github.com/gh0stzk/dotfiles
#   | |_) |__) |  __/ \ V  V / | |  | |  - z0mbi3.zk@protonmail.com
#   |____/____/|_|     \_/\_/  |_|  |_|
#                                    z0mbi3 config..


###########---------- Some important variables ----------##########

export RICETHEME=$(<$HOME/.config/bspwm/rice.cfg)
PATH="${HOME}/.config/bspwm/scripts:$PATH"
BSPDIR="${HOME}/.config/bspwm"
PDIR="${HOME}/.config/bspwm/rices/${RICETHEME}"
SFILE="${BSPDIR}/scripts/.sys"

## You can edit this.
BSPWM_BORDER='3'
BSPWM_GAP='10'

###########---------- Functions ----------##########

function get_values() {
DEFNETWORK=$(ip route | grep '^default' | awk '{print $5}' | head -n1)
CARD=$(ls -1 /sys/class/backlight/)
power_supply_files=$(ls /sys/class/power_supply/)

for file in $power_supply_files
do
	if [ -e "/sys/class/power_supply/$file/capacity" ]; then
		battery_file=$file
    fi

    if [ -e "/sys/class/power_supply/$file/online" ]; then
        adapter_file=$file
    fi
done

BATTERY="$battery_file"
ADAPTER="$adapter_file"
}

set_values() {
	if [[ "$DEFNETWORK" ]]; then
		sed -i -e "s/sys_network_interface = .*/sys_network_interface = $DEFNETWORK/g" ${BSPDIR}/scripts/system.ini
	fi
	if [[ "$ADAPTER" ]]; then
		sed -i -e "s/sys_adapter = .*/sys_adapter = $ADAPTER/g" ${BSPDIR}/scripts/system.ini
	fi
	if [[ "$BATTERY" ]]; then sed -i -e "s/sys_battery = .*/sys_battery = $BATTERY/g" ${BSPDIR}/scripts/system.ini
	fi
	if [[ "$CARD" ]]; then
		sed -i -e "s/sys_graphics_card = .*/sys_graphics_card = $CARD/g" ${BSPDIR}/scripts/system.ini
	fi
}

if [[ ! -f "$SFILE" ]]; then
	get_values
	set_values
	touch ${SFILE}
fi

function launch() {
  local running="$(pgrep -x "$1")"
  [ "$running" ] && killall -9 -q "$1"
  "$@" &
}

function killeww() {
  if pidof eww >/dev/null 2>&1; then
	pkill -f eww
  fi
}

function ReloadTerms() {
  cat ${PDIR}/alacrittyrc > $HOME/.config/alacritty/alacritty.toml
}

function SetBspwmConf() {
	bspc config border_width "$BSPWM_BORDER"
	bspc config top_padding "$2"
	bspc config bottom_padding "$3"
	bspc config normal_border_color "$4" 
	bspc config active_border_color "$5"
	bspc config focused_border_color "$6"
	bspc config presel_feedback_color "$7"
	bspc config left_padding "$8"
	bspc config right_padding "$9"
	bspc config window_gap "$BSPWM_GAP"
}

###########---------- Workspaces ----------##########

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5' '6'
		#bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' ''
		let name++
	done
}

workspaces

###########---------- Launch The Rice!! ----------##########

ReloadTerms
RandomWall

case "${RICETHEME}" in

    pamela)

		SetBspwmConf "${BSPWM_BORDER}" 60 5 "#C574DD" "#C574DD" "#8897F4" "#FF4971" 5 5 "${BSPWM_GAP}"

		#killeww
		launch polybar -q pam1 -c ${PDIR}/config.ini
		polybar -q pam2 -c ${PDIR}/config.ini &
		polybar -q pam3 -c ${PDIR}/config.ini &
		polybar -q pam4 -c ${PDIR}/config.ini &
		polybar -q pam5 -c ${PDIR}/config.ini &
		polybar -q pam6 -c ${PDIR}/config.ini &
		launch dunst -config ${BSPDIR}/dunstrc-dark
		;;

	gruvbox)

        #Default border
		# SetBspwmConf "${BSPWM_BORDER}" 10 60 "#9bced7" "#9bced7" "#c3a5e6" "#c3a5e6" 5 5 "${BSPWM_GAP}"
		# SetBspwmConf "${BSPWM_BORDER}" 10 60 "#98971a" "#98971a" "#d65d0e" "#d65d0e" 5 5 "${BSPWM_GAP}"

    # For top bar
		SetBspwmConf "${BSPWM_BORDER}" 10 10 "#98971a" "#98971a" "#d65d0e" "#d65d0e" 5 5 "${BSPWM_GAP}"

		#killeww
		
		#default rice bar
		#launch polybar -q arsen-bar -c ${PDIR}/config.ini
		#main bar
		launch polybar -q main -c ${PDIR}/polybar/config.ini
		launch dunst -config ${BSPDIR}/dunstrc-dark
		;;

    glow)

        ;;


esac

###########---------- BSPWM Config ----------##########

setxkbmap -option grp:alt_shift_toggle us,ru,ua &

bspc config external_rules_command ${BSPDIR}/scripts/ExternalRules

bspc config single_monocle                true
bspc config split_ratio                   0.5
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true
bspc config center_pseudo_tiled			  true

bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner

bspc config automatic_scheme              longest_side
bspc config initial_polarity              second_child

bspc config remove_disabled_monitors      true 
bspc config merge_overlapping_monitors    true

bspc config pointer_motion_interval       16

###########---------- AutoStart Apps ----------##########

launch sxhkd -c ${BSPDIR}/sxhkdrc
launch picom --config ${PDIR}/picom.conf
#launch picom --legacy-backends --config ${BSPDIR}/rices/"${RICETHEME}"/picom.conf
#nitrogen --restore &
xsetroot -cursor_name left_ptr
	
if [[ ! `pidof polkit-gnome-authentication-agent-1` ]]; then
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi
