#!/usr/bin/env bash

#	Simple script to hide/unhide polybar
#   Author: z0mbi3
#	url: https://github.com/gh0stzk

function hide() {
	
	if [[ "${RICETHEME}" == pamela ]]; then
		polybar-msg cmd hide | bspc config top_padding 5
		
	elif [[ "${RICETHEME}" == gruvbox ]]; then
		# polybar-msg cmd hide | bspc config bottom_padding 5
		polybar-msg cmd hide | bspc config top_padding 5
	else 
		echo "Error: Something fails dud.."
	fi
}

function unhide() {
	
	if [[ "${RICETHEME}" == pamela ]]; then
		polybar-msg cmd show | bspc config top_padding 60
		
	elif [[ "${RICETHEME}" == gruvbox ]]; then
		# polybar-msg cmd show | bspc config bottom_padding 60

    # for top bar
		polybar-msg cmd show | bspc config top_padding 60
		
	else 
		echo "Error: Something fails dud.."
	fi
}

case $1 in
	-h | --hide | hide)
		hide
		exit;;
	-u | --unhide | unhide)
		unhide
		exit;;
	*) # Invalid option
		echo "Error: Invalid option"
		exit;;
esac
