require("losthope.plugins-setup")
require("losthope.core.options")
require("losthope.core.keymaps")
require("losthope.core.colorscheme")
require("losthope.core.terminal")

require("losthope.plugins.nvim-tree")
require("losthope.plugins.lualine")
require("losthope.plugins.colorizer")
require("losthope.plugins.autopairs")
require("losthope.plugins.git")
require("losthope.plugins.treesitter")
require("losthope.plugins.lang-server")
require("losthope.plugins.notifier")
