require("losthope.plugins-setup")
require("losthope.core.options")
require("losthope.core.keymaps")
require("losthope.core.colorscheme")
require("losthope.core.terminal")

require("losthope.lib.icons")

require("losthope.plugins.lang-server")
require("losthope.plugins.nvim-tree")
require("losthope.plugins.lualine")
require("losthope.plugins.colorizer")
require("losthope.plugins.autopairs")
require("losthope.plugins.gitsigns")
require("losthope.plugins.treesitter")
require("losthope.plugins.formatter")
require("losthope.plugins.vimtex")
require("losthope.plugins.project")
